<?php
/**
 * ExMachina Framework
 *
 * WARNING: This file is part of the core ExMachina Framework DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Footer
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://machinathemes.com
 */

add_action( 'wp_footer', 'exmachina_custom_footer_scripts' );

 /* footer insert to the footer. */
add_action( exmachina_get_prefix() . '_footer', 'exmachina_custom_footer_insert' );


/**
 * Echo the footer scripts, defined in Theme Settings.
 */
function exmachina_custom_footer_scripts() {

  echo exmachina_get_option( 'footer_scripts' );

}


function exmachina_default_footer_insert() {

  /* Get the theme prefix. */
  $prefix = exmachina_get_prefix();

  /* Get theme-supported meta boxes for the settings page. */
  $supports = get_theme_support( 'exmachina-core-theme-settings' );

  /* If the current theme supports the footer meta box and shortcodes, add default footer settings. */
  if ( is_array( $supports[0] ) && in_array( 'footer', $supports[0] ) && current_theme_supports( 'exmachina-core-shortcodes' ) ) {

    /* If there is a child theme active, add the [child-link] shortcode to the $footer_insert. */
    if ( is_child_theme() )
      $settings = '<p class="copyright">' . __( 'Copyright &#169; [the-year] [site-link].', 'exmachina-core' ) . '</p>' . "\n\n" . '<p class="credit">' . __( 'Powered by [wp-link], [theme-link], and [child-link].', 'exmachina-core' ) . '</p>';

    /* If no child theme is active, leave out the [child-link] shortcode. */
    else
      $settings = '<p class="copyright">' . __( 'Copyright &#169; [the-year] [site-link].', 'exmachina-core' ) . '</p>' . "\n\n" . '<p class="credit">' . __( 'Powered by [wp-link] and [theme-link].', 'exmachina-core' ) . '</p>';
  }

  /* Return the $settings array and provide a hook for overwriting the default settings. */
  return apply_filters( "{$prefix}_default_theme_settings", $settings );

}

function exmachina_custom_footer_insert() {

  echo '<div class="footer-content footer-insert">';

  echo exmachina_get_option( 'footer_insert' );

  echo '</div>';
}
