<?php
/**
 * ExMachina Framework
 *
 * WARNING: This file is part of the core ExMachina Framework DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Footer
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://machinathemes.com
 */

add_action( 'wp_footer', 'exmachina_custom_footer_scripts' );

 /* footer insert to the footer. */
add_action( exmachina_get_prefix() . '_footer', 'exmachina_custom_footer_insert' );


/**
 * Echo the footer scripts, defined in Theme Settings.
 */
function exmachina_custom_footer_scripts() {

  echo exmachina_get_option( 'footer_scripts' );

}


function exmachina_default_footer_insert() {

  $settings = '<p class="copyright">' . __( 'Copyright &#169; [the-year] [site-link].', 'exmachina-core' ) . '</p>' . "\n\n" . '<p class="credit">' . __( 'Powered by [wp-link] and [theme-link].', 'exmachina-core' ) . '</p>';

  return $settings;

}

function exmachina_custom_footer_insert() {

  echo '<div class="footer-content footer-insert">';

  echo exmachina_get_option( 'footer_insert' );

  echo '</div>';
}
