<?php
/**
 * ExMachina Framework
 *
 * WARNING: This file is part of the core ExMachina Framework DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Sidebars
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://machinathemes.com
 */


/* Add the primary sidebars after the main content. */
add_action( exmachina_get_prefix() . '_after_main', 'exmachina_after_main' );

/* Filter the sidebar widgets. */
add_filter( 'sidebars_widgets', 'exmachina_disable_sidebars' );
add_action( 'template_redirect', 'exmachina_one_column' );

/* Allow developers to filter the default sidebar arguments. */
add_filter( exmachina_get_prefix() . '_sidebar_defaults', 'exmachina_sidebar_defaults' );

/**
 * Display sidebar
 */
function exmachina_after_main() {
  get_sidebar();
}

/**
 * Disables sidebars if viewing a one-column page.
 */

function exmachina_disable_sidebars( $sidebars_widgets ) {
  global $wp_customize;

  $customize = ( is_object( $wp_customize ) && $wp_customize->is_preview() ) ? true : false;

  if ( !is_admin() && !$customize && '1c' == get_theme_mod( 'theme_layout' ) )
    $sidebars_widgets['primary'] = false;

  return $sidebars_widgets;
}

/**
 * Function for deciding which pages should have a one-column layout.
 */
function exmachina_one_column() {

  if ( !is_active_sidebar( 'primary' ) )
    add_filter( 'theme_mod_theme_layout', 'exmachina_theme_layout_one_column' );

  elseif ( is_attachment() && wp_attachment_is_image() && 'default' == get_post_layout( get_queried_object_id() ) )
    add_filter( 'theme_mod_theme_layout', 'exmachina_theme_layout_one_column' );

}


/**
 * Filters 'get_theme_layout' by returning 'layout-1c'.
 */
function exmachina_theme_layout_one_column( $layout ) {
  return '1c';
}

function exmachina_sidebar_defaults($defaults) {
  /* Set up some default sidebar arguments. */
  $defaults = array(
    'before_widget' => '<section id="%1$s" class="widget %2$s widget-%2$s"><div class="widget-wrap">',
    'after_widget'  => '</div></section>',
    'before_title'  => '<h3 class="widget-title">',
    'after_title'   => '</h3>'
  );

  return $defaults;
}